name: Lint and Check Types
on: push

jobs:
  ci:
    name: Lint and Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm eslint . --max-warnings 0
      - run: pnpm tsc
